/*
 * generated by Xtext
 */
package org.br.excel.exceldsl.ui.contentassist

import org.br.excel.exceldsl.ui.contentassist.AbstractExcelDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExcelDSLProposalProvider extends AbstractExcelDSLProposalProvider {
}
