/*
 * generated by Xtext
 */
package org.br.excel.exceldsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExcelDSLUiModule extends org.br.excel.exceldsl.ui.AbstractExcelDSLUiModule {
	public ExcelDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
