/*
 * generated by Xtext
 */
package org.br.excel.exceldsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.br.excel.exceldsl.ui.internal.ExcelDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExcelDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExcelDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExcelDSLActivator.getInstance().getInjector(ExcelDSLActivator.ORG_BR_EXCEL_EXCELDSL_EXCELDSL);
	}
	
}
