/**
 * generated by Xtext
 */
package org.br.excel.exceldsl.validation;

import org.br.excel.exceldsl.validation.AbstractExcelDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ExcelDSLValidator extends AbstractExcelDSLValidator {
}
