/*
* generated by Xtext
*/
package org.br.excel.exceldsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.br.excel.exceldsl.services.ExcelDSLGrammarAccess;

public class ExcelDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExcelDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.br.excel.exceldsl.parser.antlr.internal.InternalExcelDSLParser createParser(XtextTokenStream stream) {
		return new org.br.excel.exceldsl.parser.antlr.internal.InternalExcelDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Excel";
	}
	
	public ExcelDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExcelDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
